= Билеты по алгоритмам
:lang: ru_RU
:stem: asciimath

== Теормин
Алгоритм.
Память и время как ресурсы.
Вычисление чисел Фибоначчи:
экспоненциальный рекурсивный алгоритм,
полиномиальный алгоритм.
O-символика как инструмент оценки ресурсов,
различные асимптотики (логарифм, полином, экспонента).
Все алгоритмы курса: оценки сложности и решаемые ими задачи.

== 1. Элементарные структуры данных
Массивы переменного размера:
аддитивная и мультипликативная схемы реаллокации.
Односвязный список, двусвязный список.
Абстрактные типы данных, интерфейс и реализация.
Стек, очередь, дек; моделирование на основе массива.
Моделирование очереди с помощью двух стеков.
Амортизационный анализ:
метод учётных стоимостей операций и метод предоплаты.

== 2. Разделяй и властвуй
Рекуррентные соотношения.
Метод «разделяй и властвуй».
Умножение n-битовых чисел:
простой рекурсивный алгоритм,
улучшенный рекурсивный алгоритм.
Рекуррентные соотношения: основная теорема.
Двоичный поиск.

== 3. Сортировка: квадратичные и сортировка слиянием
Квадратичные сортировки.
Сортировка слиянием: с рекурсией и без.
Нижняя оценка stem:[Omega(n log n)]
для сортировки сравнениями.

== 4. Сортировка кучей
Куча, построение кучи за линейное время.
Очередь с приоритетами на основе кучи.
Сортировка с помощью кучи, частичная сортировка.
Операции с d-ичной кучей.

== 5. Быстрая сортировка
Анализ среднего времени работы,
анализ глубины рекурсии, элиминация хвостовой рекурсии,
IntroSort, массивы с малым количеством различных элементов, QuickSort3.

== 6. Линейные сортировки и порядковые статистики
Сортировка подсчётом, стабильность.
Цифровая сортировка.
Bucket sort для равномерно распределённых вещественных чисел.
Порядковые статистики, нахождение за линейное в среднем время.
Медиана медиан.

== 7. Динамическое программирование 1
Общие принципы динамического программирования.
Кратчайшие пути в ациклических ориентированных графах.
Наибольшая возрастающая подпоследовательность:
подзадачи, порядок на подзадачах, граф подзадач,
сравнение с рекурсивным алгоритмом;
нахождение не только длины, но и самой подпоследовательности.
Дискретная задача о рюкзаке.

== 8. Динамическое программирование 2
Умножение матриц.
Независимые множества максимального веса в деревьях.
Редакционное расстояние:
граф на подзадачах, нахождение кратчайшего пути в данном графе;
вычисление редакционного расстояния с использованием линейной памяти
(алгоритм Хиршберга).

== 9. Жадные алгоритмы 1
Покрытие точек единичными отрезками.
Непрерывный рюкзак.
Задача о выборе заявок.
Максимальные независимые множества в деревьях.
Код Хаффмана.

== 10. Жадные алгоритмы 2
Минимальное покрывающее дерево:
свойство разреза, жадная стратегия,
алгоритм Прима, алгоритм Краскала.

== 11. Система непересекающихся множеств
Представление множеств с помощью деревьев, эвристики:
ранги и сжатие путей,
верхняя оценка stem:[O(m log^** n)] на время работы m операций.
Анализ учётных стоимостей операций: метод ростовщика.

== 12. Декомпозиция графов 1
Графы и способы их представления:
матрица смежности, списки смежности,
матрица инцидентности.
Поиск в глубину.
Графы и способы их представления, способы использования графов.
Поиск в глубину в неориентированных графах,
выделение компонент связности, нахождение циклов.
Поиск в глубину в ориентированных графах: поиск цикла.

== 13. Декомпозиция графов 2
Поиск в глубину в ориентированных графах:
топологическая сортировка вершин,
выделение компонент сильной связности в орграфах.

== 14. Кратчайшие пути в графах
Нахождение кратчайших путей из одной вершины
в невзвешенных графах, поиск в ширину.
Нахождение кратчайших путей из одной вершины
в графах с положительными весами, алгоритм Дейкстры,
оценка времени работы при различных реализациях очереди с приоритетами
(массивом, двоичной кучей, d-ичной кучей).

== 15. Кратчайшие пути в графах с отрицательными рёбрами
Алгоритм Беллмана-Форда, проверка наличия цикла отрицательного веса.
Кратчайшие пути в ациклических ориентированных графах.
Кратчайшие пути между всеми парами вершин: алгоритм Флойда-Уоршелла.

== Примечания
Билет состоит из двух вопросов.
При подготовке билетов пользоваться любыми источниками запрещается.
Билеты рассказываются устно.
Кроме материала билета нужно уметь отвечать и на вопросы по другим билетам.
После ответа выдаётся задача.
Перед получением билета студенту предлагается написать тест.
Оценка за тест — это максимальная оценка,
которую студент может получить за экзамен.
