== Билеты по алгоритмам
:stem: asciimath

=== Теормин

Алгоритм. Память и время как ресурсы. Вычисление чисел Фибоначчи:
экспоненциальный рекурсивный алгоритм, полиномиальный алгоритм.
O-символика как инструмент оценки ресурсов, различные асимптотики
(логарифм, полином, экспонента). Все алгоритмы курса: оценки сложности и
решаемые ими задачи.

==== Числа Фибоначчи

.Экспоненциальный алгоритм:
[source,julia]
----
function fib(n)
    if n < 2
        n
    else
        fib(n - 1) + fib(n - 2)
    end
end
----

.Полиномиальный (линейный) алгоритм:
[source,julia]
----
function fib(n)
   a = 0` +
   b = 1` +
   for i=1:n` +
       c = a + b` +
       a = b` +
       b = c` +
   end` +
   a`
end
----

.Логарифмический алгоритм:
[source,julia]
----
# Возведение матрицы в степень
using LinearAlgebra function fib(n)
   function helper(mat, pow)
       if pow <= 1
           mat
       else
           tmp = helper(mat, pow ÷ 2)
           tmp *= tmp
           if pow % 2 == 1
               tmp *= mat
           end
           tmp
       end
   end
   (helper([0 1; 1 1], n) * [0; 1])[1]
end
----

[[элементарные_структуры_данных]]
=== 1. Элементарные структуры данных

Массивы переменного размера: аддитивная и мультипликативная схемы
реаллокации. Односвязный список, двусвязный список. Абстрактные типы
данных, интерфейс и реализация. Стек, очередь, дек; моделирование на
основе массива. Моделирование очереди с помощью двух стеков.
Амортизационный анализ: метод учётных стоимостей операций и метод
предоплаты.

[[разделяй_и_властвуй]]
=== 2. Разделяй и властвуй

Рекуррентные соотношения. Метод «разделяй и властвуй». Умножение
n-битовых чисел: простой рекурсивный алгоритм, улучшенный рекурсивный
алгоритм. Рекуррентные соотношения: основная теорема. Двоичный поиск.

[[сортировка_квадратичные_и_сортировка_слиянием]]
=== 3. Сортировка: квадратичные и сортировка слиянием

Квадратичные сортировки. Сортировка слиянием: с рекурсией и без. Нижняя
оценка stem:[Omega(n log n)] для сортировки сравнениями.

[[сортировка_кучей]]
=== 4. Сортировка кучей

Куча, построение кучи за линейное время. Очередь с приоритетами на
основе кучи. Сортировка с помощью кучи, частичная сортировка. Операции с
d-ичной кучей.

[[быстрая_сортировка]]
=== 5. Быстрая сортировка

Анализ среднего времени работы, анализ глубины рекурсии, элиминация
хвостовой рекурсии, IntroSort, массивы с малым количеством различных
элементов, QuickSort3.

[[линейные_сортировки_и_порядковые_статистики]]
=== 6. Линейные сортировки и порядковые статистики

Сортировка подсчётом, стабильность. Цифровая сортировка. Bucket sort для
равномерно распределённых вещественных чисел. Порядковые статистики,
нахождение за линейное в среднем время. Медиана медиан.

[[динамическое_программирование_1]]
=== 7. Динамическое программирование 1

Общие принципы динамического программирования. Кратчайшие пути в
ациклических ориентированных графах. Наибольшая возрастающая
подпоследовательность: подзадачи, порядок на подзадачах, граф подзадач,
сравнение с рекурсивным алгоритмом; нахождение не только длины, но и
самой подпоследовательности. Дискретная задача о рюкзаке.

[[динамическое_программирование_2]]
=== 8. Динамическое программирование 2

Умножение матриц. Независимые множества максимального веса в деревьях.
Редакционное расстояние: граф на подзадачах, нахождение кратчайшего пути
в данном графе; вычисление редакционного расстояния с использованием
линейной памяти (алгоритм Хиршберга).

[[жадные_алгоритмы_1]]
=== 9. Жадные алгоритмы 1

Покрытие точек единичными отрезками. Непрерывный рюкзак. Задача о выборе
заявок. Максимальные независимые множества в деревьях. Код Хаффмана.

[[жадные_алгоритмы_2]]
=== 10. Жадные алгоритмы 2

Минимальное покрывающее дерево: свойство разреза, жадная стратегия,
алгоритм Прима, алгоритм Краскала.

[[система_непересекающихся_множеств]]
=== 11. Система непересекающихся множеств

Представление множеств с помощью деревьев, эвристики: ранги и сжатие
путей, верхняя оценка stem:[O(m log^** n)] на время работы m операций.
Анализ учётных стоимостей операций: метод ростовщика.

[[декомпозиция_графов_1]]
=== 12. Декомпозиция графов 1

Графы и способы их представления: матрица смежности, списки смежности,
матрица инцидентности. Поиск в глубину. Графы и способы их
представления, способы использования графов. Поиск в глубину в
неориентированных графах, выделение компонент связности, нахождение
циклов. Поиск в глубину в ориентированных графах: поиск цикла.

[[декомпозиция_графов_2]]
=== 13. Декомпозиция графов 2

Поиск в глубину в ориентированных графах: топологическая сортировка
вершин, выделение компонент сильной связности в орграфах.

[[кратчайшие_пути_в_графах]]
=== 14. Кратчайшие пути в графах

Нахождение кратчайших путей из одной вершины в невзвешенных графах,
поиск в ширину. Нахождение кратчайших путей из одной вершины в графах с
положительными весами, алгоритм Дейкстры, оценка времени работы при
различных реализациях очереди с приоритетами (массивом, двоичной кучей,
d-ичной кучей).

[[кратчайшие_пути_в_графах_с_отрицательными_рёбрами]]
=== 15. Кратчайшие пути в графах с отрицательными рёбрами

Алгоритм Беллмана-Форда, проверка наличия цикла отрицательного веса.
Кратчайшие пути в ациклических ориентированных графах. Кратчайшие пути
между всеми парами вершин: алгоритм Флойда-Уоршелла.

=== Примечания

Билет состоит из двух вопросов. При подготовке билетов пользоваться
любыми источниками запрещается. Билеты рассказываются устно. Кроме
материала билета нужно уметь отвечать и на вопросы по другим билетам.
После ответа выдаётся задача. Перед получением билета студенту
предлагается написать тест. Оценка за тест — это максимальная оценка,
которую студент может получить за экзамен.
